ALTER TABLE public.produtos
ADD COLUMN IF NOT EXISTS porc_bdi NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cst TEXT,
ADD COLUMN IF NOT EXISTS cest TEXT,
ADD COLUMN IF NOT EXISTS mascara_produto TEXT,
ADD COLUMN IF NOT EXISTS status_comercial TEXT DEFAULT 'Normal';
